export const SIGNUP = "SIGNUP";
export const SIGNIN = "SIGNIN";
export const LOGOUT = "LOGOUT";
export const CURRENT = "CURRENT";
export const PRODUCT = "PRODUCT";
export const GET_PRODUCT = "GET_PRODUCT";
export const RESERVATION = "RESERVATION";
export const GET_RESERVATION = "GET_RESERVATION";
export const DELETE_RESERVATION= "DELETE_RESERVATION";